#ifndef MeshServer_idl
#define MeshServer_idl

#include "BasicDataType.idl"
#include "ExtendedDataTypes.idl"
#include "InterfaceDataTypes.idl"

module RTC {

  enum RETURN_VALUE {
    RETVAL_OK,
    RETVAL_INVALID_PARAMETER,
    RETVAL_EMPTY_MAP,
    RETVAL_INVALID_PRECONDITION,
    RETVAL_NOT_IMPL,
    RETVAL_NOT_FOUND,
    RETVAL_UNKNOWN_ERROR
  };

  typedef sequence<Point3D> Mesh;

  struct Node{
    string name;
    Mesh myMesh;
    Vector3D translation;
    Vector3D rotation;
    //Node child; //Cannot create an instance of struct 'Node' inside its own definition
  };
  
  typedef sequence<Node> MultiMesh;

  typedef sequence<double> JointPose;
  typedef sequence<JointPose> JointTrajectory;

  interface MeshServer {
    RETURN_VALUE getRobotMesh(out MultiMesh robots);
    RETURN_VALUE getEnvMesh(out Node env);
  };
  
};


#endif
